public with sharing class MM_ActorWrapper {

    @AuraEnabled public boolean adult;
    @AuraEnabled public String biography;    //James Edmund Caan (/kɑːn/ KAHN; March 26, 1940 – July 6, 2022) was an American actor who was nominated for several awards, including four Golden Globes, an Emmy, and an Oscar. Caan was awarded a motion pictures star on the Hollywood Walk of Fame in 1978.
    @AuraEnabled public String birthday;
    @AuraEnabled public String deathday;    //2022-07-06
    @AuraEnabled public Integer gender;    //2
    @AuraEnabled public Integer id;    //3085
    @AuraEnabled public String imdb_id;    //nm0001001
    @AuraEnabled public String known_for_department;    //Acting
    @AuraEnabled public String name;    //James Caan
    @AuraEnabled public String place_of_birth;    //The Bronx, New York, USA
    @AuraEnabled public Double popularity;    //29.832
    @AuraEnabled public String profile_path;    ///bGyOCCOIgcIyKjOGLoXoyp0XWHf.jpg

}