global with sharing class MM_MovieActorWrapper {
     @AuraEnabled public cls_cast[] cast1;
     @AuraEnabled public cls_crew[] crew;
     @AuraEnabled public Integer id;	//3084
     public class cls_cast {
         @AuraEnabled public boolean adult;
         @AuraEnabled public String backdrop_path;	///tmU7GeKVybMWFButWEGl2M4GeiP.jpg
         @AuraEnabled public Integer[] genre_ids;
         @AuraEnabled public Integer id;	//238
         @AuraEnabled public String original_language;	//en
         @AuraEnabled public String original_title;	//The Godfather
         @AuraEnabled public String overview;	//Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.
         @AuraEnabled public Double popularity;	//99.066
         @AuraEnabled public String poster_path;	///3bhkrj58Vtu7enYsRolD1fZdja1.jpg
         @AuraEnabled public String release_date;	//1972-03-14
         @AuraEnabled public String title;	//The Godfather
         @AuraEnabled public boolean video;
         @AuraEnabled public Double vote_average;	//8.714
         @AuraEnabled public Integer vote_count;	//16577
         @AuraEnabled public String character;	//Don Vito Corleone
         @AuraEnabled public String credit_id;	//52fe422bc3a36847f8009357
         @AuraEnabled public Integer order;	//0
    }

     public class cls_crew {
         @AuraEnabled public boolean adult;
         @AuraEnabled public String backdrop_path;	///gUIVD0rFWVB8Okk8wU8dQxjOYnZ.jpg
         @AuraEnabled public Integer[] genre_ids;
         @AuraEnabled public Integer id;	//7984
         @AuraEnabled public String original_language;	//en
         @AuraEnabled public String original_title;	//In the Name of the Father
         @AuraEnabled public String overview;	//A small time thief from Belfast, Gerry Conlon, is falsely implicated in the IRA bombing of a pub that kills several people while he is in London. He and his four friends are coerced by British police into confessing their guilt. Gerry's father and other relatives in London are also implicated in the crime. He spends fifteen years in prison with his father trying to prove his innocence.
         @AuraEnabled public Double popularity;	//11.519
         @AuraEnabled public String poster_path;	///3NcIkKxaO2SmRVsG1v50XhtmL0f.jpg
         @AuraEnabled public String release_date;	//1993-12-12
         @AuraEnabled public String title;	//In the Name of the Father
         @AuraEnabled public boolean video;
         @AuraEnabled public Double vote_average;	//7.914
         @AuraEnabled public Integer vote_count;	//1399
         @AuraEnabled public String credit_id;	//5762dc22c3a36818c9000047
         @AuraEnabled public String department;	//Crew
         @AuraEnabled public String job;	//Thanks
    }
}