name: Check-Feature-Branch

on:
    push:
        branches:
            - feature
              
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
        
          - name: 'deploy'
            with:
              checkonly: true
                       
