name: Check-Feature-Branch

on:
    push:
        branches:
            - feature

jobs:
    deploy:
        runs-on: windows-latest
        steps:
            - name: 'deploy'
              checkonly: true
