name: Feature Branch Ready For Review
       
on:
    pull_request:
      branches: [ develop ]
      paths:
        - 'force-app/**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set Git config
      run: |
          git config --local user.email "julia.lenczewska@britenet.com.pl"
          git config --local user.name "jlenczewska"
          
    - name: Merge feature to dev
      run: |
          git checkout develop
          git remote add origin https://github.com/jlenczewska/Real-Estate-App.git
          git push -u origin develop
          git pull
          git merge ${{ github.head_ref }}
          
          
